{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(DCGM_FI_DEV_VGPU_LICENSE_STATUS,instance)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(DCGM_FI_DEV_DEC_UTIL{instance=~\"$instance:9400\"},device)"
    }
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "OverViews", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$instance:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_os_info{instance=~\"$instance:9100\"}",
     "legendFormat": "pretty_name"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$instance:9100\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance:9100\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'})",
     "legendFormat": "vCPUs"
    },
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'}) /2",
     "legendFormat": "Cores"
    }
   ]
  },
  {
   "title": "Load Average 1m/CPU Cores (Max : 1)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "#count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'})\r\nsum by(instance) (node_load1{job=\"GCE_vm\", instance=~\"$instance:9100\"}) / count by(instance) (node_cpu_seconds_total{mode=\"system\", instance=~\"$instance:9100\"})",
     "legendFormat": "vCPUs"
    }
   ]
  },
  {
   "title": "GPU Model Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_VGPU_LICENSE_STATUS{instance=~\"$instance:9400\"}",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "GPU Memory Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(DCGM_FI_DEV_FB_FREE{instance=~\"$instance:9400\"}+DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"})",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "CPU, Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Utilization(%)"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"} / (node_memory_MemTotal_bytes{instance=~\"$instance:9100\"})))* 100",
     "legendFormat": "Memory Utilization(%)"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance:9100\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance:9100\"} + 1))) * 100",
     "legendFormat": "SWAP Utilization (%)"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance:9100\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance:9100\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance:9100\"}",
     "legendFormat": "15m"
    },
    {
     "expr": "sum(count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU_Cores"
    },
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "CPU Utilization(%)"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance:9400\"}",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}/(DCGM_FI_DEV_FB_FREE{instance=~\"$instance:9400\"}+DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"})*100",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  { "title": "Python Batch Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Python Batch Run States (Refresh 1m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by(batch_name) (batch_process_cpu_percent{instance=~\"$instance:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python Batch Run States (Refresh 1m)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(batch_name) (batch_process_cpu_percent{instance=~\"$instance:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python Batch Process Resource Monitor",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "batch_process_cpu_percent{instance=~\"$instance:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "batch_process_mem_percent{instance=~\"$instance:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "batch_process_elapsed_seconds{instance=~\"$instance:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "batch_process_gpu_num{instance=~\"$instance:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "batch_process_gpu_used{instance=~\"$instance:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "batch_process_vram_mib{instance=~\"$instance:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "batch_process_cuda_percent_average{instance=~\"$instance:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Name",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_uname_info{instance=\"$instance:9100\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_os_info{instance=~\"$instance:9100\"}",
       "legendFormat": "pretty_name"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(time() - node_boot_time_seconds{instance=~\"$instance:9100\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'})",
       "legendFormat": "vCPUs"
      },
      {
       "expr": "count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'}) /2",
       "legendFormat": "Cores"
      }
     ]
    },
    {
     "title": "Load Average 1m/CPU Cores (Max : 1)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "#count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'})\r\nsum by(instance) (node_load1{job=\"GCE_vm\", instance=~\"$instance:9100\"}) / count by(instance) (node_cpu_seconds_total{mode=\"system\", instance=~\"$instance:9100\"})",
       "legendFormat": "vCPUs"
      }
     ]
    },
    {
     "title": "Total RAM",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance:9100\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total SWAP",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 4, "w": 4, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance:9100\"}"
      }
     ]
    },
    {
     "title": "Load Average (Last)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_load1{instance=\"$instance:9100\"}",
       "legendFormat": "Load Average 1"
      },
      {
       "expr": "node_load5{instance=\"$instance:9100\"}",
       "legendFormat": "Load Average 5"
      },
      {
       "expr": "node_load15{instance=\"$instance:9100\"}",
       "legendFormat": "Load Average 15"
      }
     ]
    },
    {
     "title": "CPU, Memory Utilization (Last)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"idle\"}[$interval])) * 100)",
       "legendFormat": "CPU Utilization(%)"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"} / (node_memory_MemTotal_bytes{instance=~\"$instance:9100\"})))* 100",
       "legendFormat": "Memory Utilization(%)"
      },
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance:9100\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance:9100\"} + 1))) * 100",
       "legendFormat": "SWAP Utilization (%)"
      }
     ]
    },
    {
     "title": "CPU Core usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\",instance=\"$instance:9100\"}[5m])) by (cpu) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "VM Batch Run States (Refresh 1m)",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "electra_process_count{instance=~\"$instance:9100\"}",
       "legendFormat": "{{tenant_number}}"
      }
     ]
    },
    {
     "title": "Disk Space Utilization (Last)",
     "type": "table-old",
     "description": "In this kanban: the total disk, usage, available, and usage rate are consistent with the values of the Size, Used, Avail, and Use% columns of the df command, and the value of Use% will be rounded to one decimal place, which will be more accurate .\n\nNote: The Use% algorithm in df is: (size-free) * 100 / (avail + (size-free)), the result is divisible by this value, non-divisible by this value is +1, and the unit of the result is %.\nRefer to the df command source code:",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
       "legendFormat": "总量"
      },
      {
       "expr": "node_filesystem_avail_bytes {instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0"
      },
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "VM Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU, Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"idle\"}[$interval])) * 100)",
       "legendFormat": "CPU Utilization(%)"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"} / (node_memory_MemTotal_bytes{instance=~\"$instance:9100\"})))* 100",
       "legendFormat": "Memory Utilization(%)"
      },
      {
       "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$instance:9100\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$instance:9100\"} + 1))) * 100",
       "legendFormat": "SWAP Utilization (%)"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "node_load1{instance=~\"$instance:9100\"}",
       "legendFormat": "1m"
      },
      {
       "expr": "node_load5{instance=~\"$instance:9100\"}",
       "legendFormat": "5m"
      },
      {
       "expr": "node_load15{instance=~\"$instance:9100\"}",
       "legendFormat": "15m"
      },
      {
       "expr": " sum(count(node_cpu_seconds_total{instance=~\"$instance:9100\", mode='system'}) by (cpu,instance)) by(instance)",
       "legendFormat": "CPU cores"
      },
      {
       "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"idle\"}[$interval])) * 100)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "Cached"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"} / (node_memory_MemTotal_bytes{instance=~\"$instance:9100\"})))* 100",
       "legendFormat": "Used%"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} - (node_memory_Cached_bytes{instance=~\"$instance:9100\"} + node_memory_Buffers_bytes{instance=~\"$instance:9100\"} + node_memory_MemFree_bytes{instance=~\"$instance:9100\"})",
       "legendFormat": "Used(total-cached-buffers-free)"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "Used(total-avail)"
      },
      {
       "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"}",
       "legendFormat": "Avvilable"
      }
     ]
    },
    {
     "title": "Disk Space Utilization ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$instance:9100',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{device}}({{mountpoint}})%"
      }
     ]
    },
    {
     "title": "Network bandwidth usage per second $device",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bps", "label": "transmit（-）/receive（+）" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{instance=~'$instance:9100'}[$interval])*8",
       "legendFormat": "{{device}}_receive"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{instance=~'$instance:9100'}[$interval])*8",
       "legendFormat": "{{device}}_transmit"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "graph",
     "description": "Per second read / write bytes ",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{instance=~\"$instance:9100\"}[$interval])",
       "legendFormat": "{{device}}_Read bytes"
      },
      {
       "expr": "rate(node_disk_written_bytes_total{instance=~\"$instance:9100\"}[$interval])",
       "legendFormat": "{{device}}_Written bytes"
      }
     ]
    },
    {
     "title": "CPU% Basic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"system\"}[$interval])) by (instance) *100",
       "legendFormat": "System"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"user\"}[$interval])) by (instance) *100",
       "legendFormat": "User"
      },
      {
       "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"iowait\"}[$interval])) by (instance) *100",
       "legendFormat": "Iowait"
      },
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"idle\"}[$interval])) by (instance))*100",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Disk IOps Completed（IOPS）",
     "type": "graph",
     "description": "Read/write completions per second\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 61 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed_total{instance=~\"$instance:9100\"}[$interval])",
       "legendFormat": "{{device}}_Reads completed"
      },
      {
       "expr": "rate(node_disk_writes_completed_total{instance=~\"$instance:9100\"}[$interval])",
       "legendFormat": "{{device}}_Writes completed"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU OverViews",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Model",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "gpu_vram_size_total{instance=~\"$instance:9100\"}",
       "legendFormat": "{{modelName}} ({{gpu}})"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Current. Utilizations",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Current. Mem_Utilizations",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}/(DCGM_FI_DEV_FB_FREE{instance=~\"$instance:9400\"}+DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"})*100",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU CUDA Core Active",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Framebuffer Size (USED VRAM SIZE)",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU info",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "gpu_vram_size_total{instance=~\"$instance:9100\"}",
       "legendFormat": "{{modelName}}_{{gpu}}"
      }
     ]
    },
    {
     "title": "GPU PowerUsage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU SM Clock",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"$instance:9400\"} * 1000000",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Mem Clock",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_MEM_CLOCK{instance=~\"$instance:9400\"} * 1000000",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Tensor Core Active",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 17 },
     "options": {
      "content": "# *  Nvidia T4 Spec\n\n### - 적정 온도 \n- 60 ~ 70 °C\n- 85°C 이상이면 하드웨어 문제 발생 가능\n\n### - TDP : 70W \n- 75.4W 까지는 ok\n- TDP초과시 최대 성능 모드로 동작\n\n### - Vram : 16GB \n- Framebuffer Memory Used : Vram 사용량\n- Memory Utilization : Vram 사용률 \n  - 메모리 부족 시 배치 실행 도중 OOM Killer 발생 가능\n  - 95% 이상인 경우 Alert 발생 \n\n### - GPU SM Clock \n- 1.0Ghz 이하 : GPU 유휴 혹은 부하 낮음\n- 1.0 ~ 1.59Ghz : 정상 부하 \n- 1.7Ghz 이상 : 높은 부하 발생\n\n### - GPU Memory Clock \n- 기본 클럭값 : 5.0Ghz\n  - 5.0Ghz 이상: 메모리 대역폭 최대 활용중 \n  - 5.0Ghz 이하 : GPU 유휴 상태 or 메모리 사용량 적은 작업 수행중\n\n### NvSwitch, NvLink\n- NvSwitch\n  - Nvidia A100 등에서 사용하는 고급 Nvidia GPU 아키텍처\n    - GPU간 연결 기술\n  - Nvidia T4는 해당 기술을 지원하지 않으므로 관련 메트릭 수집 불가\n\n- NvLink\n  - 여러 GPU를 빠르게 연결하여 데이터 전송 성능을 개선하는 기술 \n    - 주로 V100, A100 등의 고급 데이터센터 GPU에서 사용 \n  - Nvidia T4는 해당 기술을 지원하지 않으므로 관련 메트릭 수집 불가"
     }
    },
    {
     "title": "GPU Hardware Info",
     "type": "table",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance:9400\"}",
       "legendFormat": "GPU Temperature"
      },
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance:9400\"}",
       "legendFormat": "GPU Power Usage"
      },
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance:9400\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}/(DCGM_FI_DEV_FB_FREE{instance=~\"$instance:9400\"}+DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"})*100",
       "legendFormat": "__auto"
      },
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "(DCGM_FI_DEV_FB_FREE{instance=~\"$instance:9400\"}+DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"$instance:9400\"} * 1000000",
       "legendFormat": "__auto"
      },
      {
       "expr": "DCGM_FI_DEV_MEM_CLOCK{instance=~\"$instance:9400\"} * 1000000",
       "legendFormat": "__auto"
      },
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Memory utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}/(DCGM_FI_DEV_FB_FREE{instance=~\"$instance:9400\"}+DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"})*100",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU SM Clocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{instance=~\"$instance:9400\"} * 1000000",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Memory Clocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_MEM_CLOCK{instance=~\"$instance:9400\"} * 1000000",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Framebuffer Mem Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU CUDA Core Active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    },
    {
     "title": "GPU Tensor Core Active",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{instance=~\"$instance:9400\"}",
       "legendFormat": "{{modelName}}_{{device}}"
      }
     ]
    }
   ]
  }
 ]
}