{
 "title": "NVIDIA DCGM Exporter Dashboard_Edited",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_ip",
    "label": "host_ip",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name=\"dcgm-exporter\"},host_ip)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name=\"dcgm-exporter\", host_ip=~\"$host_ip\"},node)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{created_by_name=\"dcgm-exporter\", node=~\"$node\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "OverViews", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kubernetes Node Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Node's GPU State",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{pod=~\"$pod\"}",
     "legendFormat": "GPU_TEMP{{label_name}}"
    },
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{pod=~\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{pod=~\"$pod\"} * 1000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod=~\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_FB_USED{pod=~\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{pod=~\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg. Utilizations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "GPU Avg. Mem_Utilizations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_MEM_COPY_UTIL{pod=~\"$pod\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{pod=~\"$pod\"} * 1000000",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  {
   "title": "GPU Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-{{device}}({{modelName}})"
    }
   ]
  },
  {
   "title": "Metric_check (test)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "kube_pod_info ( created_by_name =~ dcgm-exporter )",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 10, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "kube_pod_info{created_by_name=~\"dcgm-exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DCGM_FI_DEV_GPU_TEMP ( pod =~ $pod )",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 10, "x": 10, "y": 44 },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{pod=~\"$pod\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}