# Python 3.9 기반 이미지 사용
FROM python:3.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY config_files/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 애플리케이션 코드 복사
COPY app.py .
RUN mkdir -p /app/variables
COPY variables/* /app/variables/

# 컨테이너 시작 시 Flask 앱 실행
CMD ["python", "app.py"]