# Dockerfile

# 베이스 이미지 선택
FROM python:3.8-slim

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 파일 복사
RUN mkdir log 
RUN mkdir config_files  
RUN mkdir static
RUN mkdir template
 
COPY app.py /app/app.py
COPY config_files/* /app/config_files/
COPY static/* /app/static/
COPY templates/* /app/templates/

# 패키지 설치
RUN pip3 install --no-cache-dir -r config_files/requirements.txt

# 포트 설정
EXPOSE 5000

# 애플리케이션 실행
CMD ["python3", "app.py"]
