FROM jenkins/jenkins:lts

USER root

# Docker 공식 GPG 키 및 저장소 추가 및 Docker CLI 설치
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release && \
    mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ARG DOCKER_GID=1001

RUN groupadd -g ${DOCKER_GID} dockergroup || true && \
    usermod -aG dockergroup jenkins

ADD ./daemon.json /etc/docker/daemon.json
RUN chown jenkins:dockergroup /etc/docker/daemon.json

USER jenkins