version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: cicd-gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost/gitlab'
    ports:
      - '8181:80'
      - '443:443'
      - '5005:5005'
      - '10022:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - cicd-network
    extra_hosts:
      - "test-cicd.com:172.22.0.100"
      - "nexus.test-cicd.com:172.22.0.100"

  jenkins:
    build:
      context: ./jenkins
      dockerfile: dockerfile
    image: myjenkins:latest
    container_name: cicd-jenkins
    restart: always
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - './jenkins/jenkins-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - cicd-network
    extra_hosts:
      - "test-cicd.com:172.22.0.100"
      - "nexus.test-cicd.com:172.22.0.100"

  nginx_proxy:
    image: nginx:latest
    container_name: cicd-nginx-proxy
    networks:
      cicd-network:
        ipv4_address: 172.22.0.100
    ports:
      - "80:80"
    volumes:
      - ./nginx_proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  sonarqube:
    image: sonarqube:latest
    container_name: cicd-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://cicd-postgresdb:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar_password
      - SONAR_WEB_CONTEXT=/sonarqube
    depends_on:
      - postgresdb
    volumes:
      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
    networks:
      - cicd-network
    extra_hosts:
      - "test-cicd.com:172.22.0.100"
      - "nexus.test-cicd.com:172.22.0.100"

  postgresdb:
    image: postgres:15
    container_name: cicd-postgresdb
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar_password
      POSTGRES_DB: sonar
    volumes:
      - ./sonarqube/postgres_data:/var/lib/postgresql/data
    networks:
      - cicd-network
    extra_hosts:
      - "test-cicd.com:172.22.0.100"
      - "nexus.test-cicd.com:172.22.0.100"

  nexus:
    image: sonatype/nexus3:latest
    container_name: cicd-nexus
    ports:
      - "8081:8081"
    volumes:
      - ./nexus/nexus-data:/opt/sonatype/sonatype-work
    restart: always
    networks:
      - cicd-network
    extra_hosts:
      - "test-cicd.com:172.22.0.100"
      - "nexus.test-cicd.com:172.22.0.100"


networks:
  cicd-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16