# Python 공식 이미지 사용
FROM python:3.11-slim

# 작업 디렉토리 생성
WORKDIR /app

# 소스 코드 복사
COPY . .

# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 포트 오픈
EXPOSE 5000

# 애플리케이션 실행
CMD ["python", "app.py"]