version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.42
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: board
      MYSQL_USER: boarduser
      MYSQL_PASSWORD: boardpass
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - boardnet

  tomcat:
    image: tomcat:9.0
    container_name: board-tomcat
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    volumes:
      - ./board.war:/usr/local/tomcat/webapps/ROOT.war
      - ./mysql-connector-java-8.0.33.jar:/usr/local/tomcat/lib/mysql-connector-java-8.0.33.jar
    depends_on:
      - mysqldb
    networks:
      - boardnet

networks:
  boardnet:

volumes:
  mysqldata:

